### ISSUE TITLE
discuss

### ISSUE THREAD

**Issue by ShionAt** [ShionAt/Keys#2]

**Comment by tikael1011** [comment]
If you would like to have an English version of readme, I can give a hand.

**Comment by ShionAt** [comment]
@tikael1011  You can help me translate an English project description, how do not tell me is oh Chinese. I've found a lot of people but nobody wants to help me.
If you really can translate correctly I need your translation / help

**Comment by tikael1011** [comment]
I checked [wikipage](https://en.wikipedia.org/wiki/QWERTY), the translation for your first four paragraphs is already there and you can quote them directly, no need to invent the wheels. However, no offense, the rest part of your readme does not look complete or convincible.

(1) As you mentioned, you may file patent application to protect your work. But readers like me are not able to figure out how your design will change the computer industry at all since you did not provide enough information. I have asked seven people (excluding me) to understand your idea. Five of them are native Chinese speakers and one among the five holds a PhD in CS, one holds a master's degree in EE and working in IC industry, and the rest are PhD students in CS. The other two, however, are American born Chinese, one is a graduate in CS, the other is an undergraduate in computer engineering and both of they can use Google Translate. Yet after reading they all gave me negative response. A simple 'no judge' comment is not an efficient way to explain your idea, even rude.

(2) You have several statements about ergonomic keyboards, the shortage of current keyboard layout and advantages of your design, any resource/paper/endorsement/experiments back you or they are just your thought?

**Comment by ShionAt** [comment]
@tikael1011 Thank you very much can you help me to translate, project introduction (README) it is not a product manual, have above illustrates only after the products will have a more detailed content/manual, as to how can bring computer ShionKeys change, have also been introduced, can't you see what it can bring change, this is the problem that everyone knowledge (knowledge to understand the surface). I'll quote you when you complete the translation. The patent has long been applied, and you can see that I am now in the stage where I can find the investment to go into production.
I don't understand why you don't speak Chinese to me

**Comment by ShionAt** [comment]
@tikael1011 If you want to get the details of the project in advance by translation, it is not advisable. I hope you will communicate with me in Chinese. I am very limited in my English language content is difficult and easy to make mistakes.

**Comment by yunFly86** [comment]
没看明白
